In [1]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [2]:
# Define the path to the two folders
folder_1_path = "dataset/byteplot/malicious/"
folder_2_path = "dataset/byteplot/benign/benign/"
folder_3_path = "dataset/byteplot/benign/benign_edu/"

# Read the images in each folder and store them in a list
images_1 = [cv2.imread(os.path.join(folder_1_path, image_file), cv2.IMREAD_GRAYSCALE) \
            for image_file in os.listdir(folder_1_path)]
images_2 = [cv2.imread(os.path.join(folder_2_path, image_file), cv2.IMREAD_GRAYSCALE) \
            for image_file in os.listdir(folder_2_path)]
images_3 = [cv2.imread(os.path.join(folder_3_path, image_file), cv2.IMREAD_GRAYSCALE) \
            for image_file in os.listdir(folder_3_path)]

In [5]:
import random

random.seed(42)

random.shuffle(images_1)

max_len_benign = len(images_2)+len(images_3)

images_1 = images_1[:max_len_benign]

In [6]:
# Label each image with the respective label (1 for total_des_trainfolder_1, 2 for folder_2)
labels_1 = [0 for _ in range(len(images_1))]
labels_2 = [1 for _ in range(len(images_2)+len(images_3))]

# Combine the images and labels into a single dataset
images = images_1 + images_2 + images_3
labels = labels_1 + labels_2

X = images
y = labels

In [7]:
# Save into numpy objects
with open('X.npy','wb') as f:
    np.save(f,X)

In [12]:
with open('y.npy', 'wb') as f:
    np.save(f,y)

In [13]:
# Load
bau = np.load('X.npy', allow_pickle=True)
miao = np.load('y.npy', allow_pickle=True)

In [11]:
bau

array([array([[ 80,  75,   3, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ..., 106, 195,  48],
       ...,
       [128, 251, 242, ...,   0,   0,   0],
       [  0,   0, 232, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8),
       array([[208, 207,  17, ..., 255, 255, 255],
       [236, 165, 193, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [ 73,  68,  61, ...,  10,   0,   0],
       [ 80,   0,  82, ...,   0,   0,   0],
       [  0,  77,  83, ...,   0,   0,   0]], dtype=uint8),
       array([[208, 207,  17, ..., 255, 255, 255],
       [236, 165, 193, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [ 32,  32,  32, ...,  32,  32,  32],
       [ 32,  32,  32, ...,  32,  32,  32],
       [ 32,  32,  32, ...,   0,   0,   0]], dtype=uint8),
       ...,
       array([[ 80,  75,   3, ...,   0,   0,   0],
       [  0,   0,   0, ...,  12,  10, 162],